export interface Departement {
  slug: string;
  name: string;
  code: string;
  region: string;
  prefecture: string;
}

export const departements: Departement[] = [
  { slug: 'ain', name: 'Ain', code: '01', region: 'Auvergne-Rhône-Alpes', prefecture: 'Bourg-en-Bresse' },
  { slug: 'aisne', name: 'Aisne', code: '02', region: 'Hauts-de-France', prefecture: 'Laon' },
  { slug: 'allier', name: 'Allier', code: '03', region: 'Auvergne-Rhône-Alpes', prefecture: 'Moulins' },
  { slug: 'alpes-de-haute-provence', name: 'Alpes-de-Haute-Provence', code: '04', region: 'Provence-Alpes-Côte d\'Azur', prefecture: 'Digne-les-Bains' },
  { slug: 'hautes-alpes', name: 'Hautes-Alpes', code: '05', region: 'Provence-Alpes-Côte d\'Azur', prefecture: 'Gap' },
  { slug: 'alpes-maritimes', name: 'Alpes-Maritimes', code: '06', region: 'Provence-Alpes-Côte d\'Azur', prefecture: 'Nice' },
  { slug: 'ardeche', name: 'Ardèche', code: '07', region: 'Auvergne-Rhône-Alpes', prefecture: 'Privas' },
  { slug: 'ardennes', name: 'Ardennes', code: '08', region: 'Grand Est', prefecture: 'Charleville-Mézières' },
  { slug: 'ariege', name: 'Ariège', code: '09', region: 'Occitanie', prefecture: 'Foix' },
  { slug: 'aube', name: 'Aube', code: '10', region: 'Grand Est', prefecture: 'Troyes' },
  { slug: 'aude', name: 'Aude', code: '11', region: 'Occitanie', prefecture: 'Carcassonne' },
  { slug: 'aveyron', name: 'Aveyron', code: '12', region: 'Occitanie', prefecture: 'Rodez' },
  { slug: 'bouches-du-rhone', name: 'Bouches-du-Rhône', code: '13', region: 'Provence-Alpes-Côte d\'Azur', prefecture: 'Marseille' },
  { slug: 'calvados', name: 'Calvados', code: '14', region: 'Normandie', prefecture: 'Caen' },
  { slug: 'cantal', name: 'Cantal', code: '15', region: 'Auvergne-Rhône-Alpes', prefecture: 'Aurillac' },
  { slug: 'charente', name: 'Charente', code: '16', region: 'Nouvelle-Aquitaine', prefecture: 'Angoulême' },
  { slug: 'charente-maritime', name: 'Charente-Maritime', code: '17', region: 'Nouvelle-Aquitaine', prefecture: 'La Rochelle' },
  { slug: 'cher', name: 'Cher', code: '18', region: 'Centre-Val de Loire', prefecture: 'Bourges' },
  { slug: 'correze', name: 'Corrèze', code: '19', region: 'Nouvelle-Aquitaine', prefecture: 'Tulle' },
  { slug: 'corse-du-sud', name: 'Corse-du-Sud', code: '2A', region: 'Corse', prefecture: 'Ajaccio' },
  { slug: 'haute-corse', name: 'Haute-Corse', code: '2B', region: 'Corse', prefecture: 'Bastia' },
  { slug: 'cote-d-or', name: 'Côte-d\'Or', code: '21', region: 'Bourgogne-Franche-Comté', prefecture: 'Dijon' },
  { slug: 'cotes-d-armor', name: 'Côtes-d\'Armor', code: '22', region: 'Bretagne', prefecture: 'Saint-Brieuc' },
  { slug: 'creuse', name: 'Creuse', code: '23', region: 'Nouvelle-Aquitaine', prefecture: 'Guéret' },
  { slug: 'dordogne', name: 'Dordogne', code: '24', region: 'Nouvelle-Aquitaine', prefecture: 'Périgueux' },
  { slug: 'doubs', name: 'Doubs', code: '25', region: 'Bourgogne-Franche-Comté', prefecture: 'Besançon' },
  { slug: 'drome', name: 'Drôme', code: '26', region: 'Auvergne-Rhône-Alpes', prefecture: 'Valence' },
  { slug: 'eure', name: 'Eure', code: '27', region: 'Normandie', prefecture: 'Évreux' },
  { slug: 'eure-et-loir', name: 'Eure-et-Loir', code: '28', region: 'Centre-Val de Loire', prefecture: 'Chartres' },
  { slug: 'finistere', name: 'Finistère', code: '29', region: 'Bretagne', prefecture: 'Quimper' },
  { slug: 'gard', name: 'Gard', code: '30', region: 'Occitanie', prefecture: 'Nîmes' },
  { slug: 'haute-garonne', name: 'Haute-Garonne', code: '31', region: 'Occitanie', prefecture: 'Toulouse' },
  { slug: 'gers', name: 'Gers', code: '32', region: 'Occitanie', prefecture: 'Auch' },
  { slug: 'gironde', name: 'Gironde', code: '33', region: 'Nouvelle-Aquitaine', prefecture: 'Bordeaux' },
  { slug: 'herault', name: 'Hérault', code: '34', region: 'Occitanie', prefecture: 'Montpellier' },
  { slug: 'ille-et-vilaine', name: 'Ille-et-Vilaine', code: '35', region: 'Bretagne', prefecture: 'Rennes' },
  { slug: 'indre', name: 'Indre', code: '36', region: 'Centre-Val de Loire', prefecture: 'Châteauroux' },
  { slug: 'indre-et-loire', name: 'Indre-et-Loire', code: '37', region: 'Centre-Val de Loire', prefecture: 'Tours' },
  { slug: 'isere', name: 'Isère', code: '38', region: 'Auvergne-Rhône-Alpes', prefecture: 'Grenoble' },
  { slug: 'jura', name: 'Jura', code: '39', region: 'Bourgogne-Franche-Comté', prefecture: 'Lons-le-Saunier' },
  { slug: 'landes', name: 'Landes', code: '40', region: 'Nouvelle-Aquitaine', prefecture: 'Mont-de-Marsan' },
  { slug: 'loir-et-cher', name: 'Loir-et-Cher', code: '41', region: 'Centre-Val de Loire', prefecture: 'Blois' },
  { slug: 'loire', name: 'Loire', code: '42', region: 'Auvergne-Rhône-Alpes', prefecture: 'Saint-Étienne' },
  { slug: 'haute-loire', name: 'Haute-Loire', code: '43', region: 'Auvergne-Rhône-Alpes', prefecture: 'Le Puy-en-Velay' },
  { slug: 'loire-atlantique', name: 'Loire-Atlantique', code: '44', region: 'Pays de la Loire', prefecture: 'Nantes' },
  { slug: 'loiret', name: 'Loiret', code: '45', region: 'Centre-Val de Loire', prefecture: 'Orléans' },
  { slug: 'lot', name: 'Lot', code: '46', region: 'Occitanie', prefecture: 'Cahors' },
  { slug: 'lot-et-garonne', name: 'Lot-et-Garonne', code: '47', region: 'Nouvelle-Aquitaine', prefecture: 'Agen' },
  { slug: 'lozere', name: 'Lozère', code: '48', region: 'Occitanie', prefecture: 'Mende' },
  { slug: 'maine-et-loire', name: 'Maine-et-Loire', code: '49', region: 'Pays de la Loire', prefecture: 'Angers' },
  { slug: 'manche', name: 'Manche', code: '50', region: 'Normandie', prefecture: 'Saint-Lô' },
  { slug: 'marne', name: 'Marne', code: '51', region: 'Grand Est', prefecture: 'Châlons-en-Champagne' },
  { slug: 'haute-marne', name: 'Haute-Marne', code: '52', region: 'Grand Est', prefecture: 'Chaumont' },
  { slug: 'mayenne', name: 'Mayenne', code: '53', region: 'Pays de la Loire', prefecture: 'Laval' },
  { slug: 'meurthe-et-moselle', name: 'Meurthe-et-Moselle', code: '54', region: 'Grand Est', prefecture: 'Nancy' },
  { slug: 'meuse', name: 'Meuse', code: '55', region: 'Grand Est', prefecture: 'Bar-le-Duc' },
  { slug: 'morbihan', name: 'Morbihan', code: '56', region: 'Bretagne', prefecture: 'Vannes' },
  { slug: 'moselle', name: 'Moselle', code: '57', region: 'Grand Est', prefecture: 'Metz' },
  { slug: 'nievre', name: 'Nièvre', code: '58', region: 'Bourgogne-Franche-Comté', prefecture: 'Nevers' },
  { slug: 'nord', name: 'Nord', code: '59', region: 'Hauts-de-France', prefecture: 'Lille' },
  { slug: 'oise', name: 'Oise', code: '60', region: 'Hauts-de-France', prefecture: 'Beauvais' },
  { slug: 'orne', name: 'Orne', code: '61', region: 'Normandie', prefecture: 'Alençon' },
  { slug: 'pas-de-calais', name: 'Pas-de-Calais', code: '62', region: 'Hauts-de-France', prefecture: 'Arras' },
  { slug: 'puy-de-dome', name: 'Puy-de-Dôme', code: '63', region: 'Auvergne-Rhône-Alpes', prefecture: 'Clermont-Ferrand' },
  { slug: 'pyrenees-atlantiques', name: 'Pyrénées-Atlantiques', code: '64', region: 'Nouvelle-Aquitaine', prefecture: 'Pau' },
  { slug: 'hautes-pyrenees', name: 'Hautes-Pyrénées', code: '65', region: 'Occitanie', prefecture: 'Tarbes' },
  { slug: 'pyrenees-orientales', name: 'Pyrénées-Orientales', code: '66', region: 'Occitanie', prefecture: 'Perpignan' },
  { slug: 'bas-rhin', name: 'Bas-Rhin', code: '67', region: 'Grand Est', prefecture: 'Strasbourg' },
  { slug: 'haut-rhin', name: 'Haut-Rhin', code: '68', region: 'Grand Est', prefecture: 'Colmar' },
  { slug: 'rhone', name: 'Rhône', code: '69', region: 'Auvergne-Rhône-Alpes', prefecture: 'Lyon' },
  { slug: 'haute-saone', name: 'Haute-Saône', code: '70', region: 'Bourgogne-Franche-Comté', prefecture: 'Vesoul' },
  { slug: 'saone-et-loire', name: 'Saône-et-Loire', code: '71', region: 'Bourgogne-Franche-Comté', prefecture: 'Mâcon' },
  { slug: 'sarthe', name: 'Sarthe', code: '72', region: 'Pays de la Loire', prefecture: 'Le Mans' },
  { slug: 'savoie', name: 'Savoie', code: '73', region: 'Auvergne-Rhône-Alpes', prefecture: 'Chambéry' },
  { slug: 'haute-savoie', name: 'Haute-Savoie', code: '74', region: 'Auvergne-Rhône-Alpes', prefecture: 'Annecy' },
  { slug: 'paris', name: 'Paris', code: '75', region: 'Île-de-France', prefecture: 'Paris' },
  { slug: 'seine-maritime', name: 'Seine-Maritime', code: '76', region: 'Normandie', prefecture: 'Rouen' },
  { slug: 'seine-et-marne', name: 'Seine-et-Marne', code: '77', region: 'Île-de-France', prefecture: 'Melun' },
  { slug: 'yvelines', name: 'Yvelines', code: '78', region: 'Île-de-France', prefecture: 'Versailles' },
  { slug: 'deux-sevres', name: 'Deux-Sèvres', code: '79', region: 'Nouvelle-Aquitaine', prefecture: 'Niort' },
  { slug: 'somme', name: 'Somme', code: '80', region: 'Hauts-de-France', prefecture: 'Amiens' },
  { slug: 'tarn', name: 'Tarn', code: '81', region: 'Occitanie', prefecture: 'Albi' },
  { slug: 'tarn-et-garonne', name: 'Tarn-et-Garonne', code: '82', region: 'Occitanie', prefecture: 'Montauban' },
  { slug: 'var', name: 'Var', code: '83', region: 'Provence-Alpes-Côte d\'Azur', prefecture: 'Toulon' },
  { slug: 'vaucluse', name: 'Vaucluse', code: '84', region: 'Provence-Alpes-Côte d\'Azur', prefecture: 'Avignon' },
  { slug: 'vendee', name: 'Vendée', code: '85', region: 'Pays de la Loire', prefecture: 'La Roche-sur-Yon' },
  { slug: 'vienne', name: 'Vienne', code: '86', region: 'Nouvelle-Aquitaine', prefecture: 'Poitiers' },
  { slug: 'haute-vienne', name: 'Haute-Vienne', code: '87', region: 'Nouvelle-Aquitaine', prefecture: 'Limoges' },
  { slug: 'vosges', name: 'Vosges', code: '88', region: 'Grand Est', prefecture: 'Épinal' },
  { slug: 'yonne', name: 'Yonne', code: '89', region: 'Bourgogne-Franche-Comté', prefecture: 'Auxerre' },
  { slug: 'territoire-de-belfort', name: 'Territoire de Belfort', code: '90', region: 'Bourgogne-Franche-Comté', prefecture: 'Belfort' },
  { slug: 'essonne', name: 'Essonne', code: '91', region: 'Île-de-France', prefecture: 'Évry-Courcouronnes' },
  { slug: 'hauts-de-seine', name: 'Hauts-de-Seine', code: '92', region: 'Île-de-France', prefecture: 'Nanterre' },
  { slug: 'seine-saint-denis', name: 'Seine-Saint-Denis', code: '93', region: 'Île-de-France', prefecture: 'Bobigny' },
  { slug: 'val-de-marne', name: 'Val-de-Marne', code: '94', region: 'Île-de-France', prefecture: 'Créteil' },
  { slug: 'val-d-oise', name: 'Val-d\'Oise', code: '95', region: 'Île-de-France', prefecture: 'Cergy' },
];

export function getDepartementBySlug(slug: string): Departement | undefined {
  return departements.find((d) => d.slug === slug);
}
